name: PR Validation

on:
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup Node.js environment
      uses: actions/setup-node@v1.4.4
      with:
        node-version: 16.x

    - name: install dependencies
      run: yarn

    - name: Run build
      run: yarn build
      env:
        HOST: ${{secrets.HOST}}
        PORT: ${{secrets.PORT}}
        APP_KEYS: ${{secrets.APP_KEYS}}
        API_TOKEN_SALT: ${{secrets.API_TOKEN_SALT}}
        ADMIN_JWT_SECRET: ${{secrets.ADMIN_JWT_SECRET}}
        JWT_SECRET: ${{secrets.JWT_SECRET}}
        APP_PROTHEUS_API_URL: ${{secrets.APP_PROTHEUS_API_URL}}
